apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka
    component: kafka-enricher
  name: ks-enricher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-enricher
    spec:
      containers:
      - name: ks-enricher
        image: enricher:v0.1
        env:
          - name: APPLICATION_ID
            value: "my-kubernetes-enricher-id"
          - name: KAFKA_BOOTSTRAP_SERVER
            value: kafka:9092
          - name: ZOOKEEPER_CONNECT
            value: zookeeper-svc:2181
          - name: NUM_STREAM_THREADS
            value: "1"
          - name: METRIC_ENABLE
            value: "true"
          - name: MULTI_ID
            value: "false"